# This file contains all the environment variables required by the application.
#
# You should copy it to #{Rails.root}/config/env.local.yml and customize the
# db_* and passmaster_host settings to suit your local environment.

development:
  db_username: postgres
  db_password:
  db_database: passmaster
  db_host: 127.0.0.1
  db_port: 5432

test:
  db_username: postgres
  db_password:
  db_database: passmaster_test
  db_host: 127.0.0.1
  db_port: 5432

staging:
  db_username: postgres
  db_password:
  db_database: passmaster
  db_host: 127.0.0.1
  db_port: 5432

production:
  db_username:
  db_password:
  db_database:
  db_host:
  db_port:
  secret_key_base:

newrelic_license_key:
passmaster_host: 127.0.0.1:8000
